import { TaskDetailPanel } from '@/components/detail/TaskDetailPanel';
import { TreeView } from '@/components/tree/TreeView';
import { Button } from '@/components/ui/button';
import { task2Api } from '@/lib/task2-api';
// import { mockTaskApi as task2Api } from '@/lib/mock-task-api';
import { useProjectStore } from '@/stores/projectStore';
import { TreeNode } from '@/types/objects';
import { Database, FolderTree, Plus, RefreshCw } from 'lucide-react';
import React, { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

export function GreenfieldLayout() {
  const {
      tasks,
      fetchTasks,
      isLoading,
      createTask,
      updateTask
  } = useProjectStore();

  const [selectedId, setSelectedId] = React.useState<string | null>(null);
  const [isSeeding, setIsSeeding] = useState(false);

  // Initial Fetch on Mount
  useEffect(() => {
      fetchTasks();
  }, []);

  // Simple Flat-to-Tree for now
  const treeData = useMemo(() => {
      const taskMap = new Map<string, TreeNode>();
      const roots: TreeNode[] = [];

      // Pass 1: Create nodes
      tasks.forEach(task => {
          taskMap.set(task.id, { ...task, children: [], level: task.task_type as any || 'task' });
      });

      // Pass 2: Connect
      tasks.forEach(task => {
         const node = taskMap.get(task.id)!;
         if (task.parent_task_id && taskMap.has(task.parent_task_id)) {
             taskMap.get(task.parent_task_id)!.children!.push(node);
         } else {
             roots.push(node);
         }
      });

      return roots;
  }, [tasks]);

  const selectedTask = useMemo(() => {
      return tasks.find(t => t.id === selectedId) || null;
  }, [selectedId, tasks]);

  const handleSmartSeed = async () => {
    setIsSeeding(true);
    try {
        // 1. Ensure Project
        const projects = await task2Api.getProjects();
        const projectKey = "P-greenfield-alpha";
        let project = projects.find(p => p.id === projectKey);

        if (!project) {
            // @ts-ignore
            project = await task2Api.createProject({
                id: projectKey,
                name: "Greenfield Project Alpha",
                description: "Validation of new frontend",
                mission: "Validation of new frontend capabilities",
                status: "planning",
                start_date: new Date().toISOString().split('T')[0],
                owner: "greenfield-user"
            });
            if (project) toast.info("Created 'Greenfield Project Alpha'");
        }

        // 2. Ensure Sprint
        const sprints = await task2Api.getSprints(project?.id);
        const sprintKey = "S-greenfield-sprint-1";
        let sprint = sprints.find(s => s.id === sprintKey);

        if (!sprint && project) {
            sprint = await task2Api.createSprint({
                id: sprintKey,
                name: "Sprint 1: Foundation",
                goal: "Launch MVP",
                cadence: "biweekly",
                primary_project: project.id,
                status: "planning",
                start_date: new Date().toISOString().split('T')[0],
                end_date: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
                owner: "greenfield-user"
            });
            if (sprint) toast.info("Created 'Sprint 1: Foundation'");
        }

        // 3. Create Task
        if (project && sprint) {
            // Semantic Task ID
            const taskId = `T-greenfield-auth-${Math.floor(Math.random() * 1000).toString().padStart(3, '0')}`;

            const newTaskPayload: any = {
                id: taskId,
                title: `Implement Authentication ${taskId}`,
                primary_project: project.id,
                primary_sprint: sprint.id,
                status: "new",
                priority: "p2",
                owner: "greenfield-user",
                summary: "Generated by Smart Seeder",
                description: "This task was created by the Smart Seeder with Semantic IDs.",
                task_type: "task"
            };

            const created = await createTask(newTaskPayload);
            if (created) {
                toast.success(`Created Task: ${created.title}`);
            } else {
                toast.error("Failed to create task");
            }
        }
    } catch (e) {
        console.error("Seeding Failed:", e);
        toast.error("Seeding Failed: " + String(e));
    } finally {
        setIsSeeding(false);
    }
  };

  const handleSaveTask = async (taskId: string, updates: any) => {
      await updateTask(taskId, updates);
      toast.success("Task Updated");
  };

  return (
    <div className="flex h-screen bg-slate-950 overflow-hidden text-slate-100">

      {/* SIDEBAR (Tree) */}
      <div className="w-[400px] flex flex-col border-r border-white/10 bg-slate-900/50">
        <div className="p-4 border-b border-white/5 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
                <div className="p-1.5 bg-cyan-500/10 rounded-md">
                    <FolderTree className="w-5 h-5 text-cyan-400" />
                </div>
                <h2 className="font-semibold text-sm tracking-wide text-muted-foreground">PROJECT EXPLORER</h2>
            </div>
            <div className="flex gap-1">
                <Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => fetchTasks()} title="Refresh">
                    <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
                </Button>
                <Button size="icon" variant="ghost" className="h-7 w-7" onClick={handleSmartSeed} disabled={isSeeding} title="Smart Seed">
                    {isSeeding ? <Database className="w-4 h-4 animate-pulse text-yellow-500" /> : <Plus className="w-4 h-4" />}
                </Button>
            </div>
        </div>

        <div className="flex-1 overflow-hidden p-2">
            <TreeView
                data={treeData}
                onSelectNode={(node) => setSelectedId(node.id)}
                className="h-full"
            />
        </div>

        <div className="p-2 border-t border-white/5 bg-slate-950/30 text-[10px] text-muted-foreground text-center font-mono">
            {tasks.length} Objects • DB Connection Active
        </div>
      </div>

      {/* MAIN CONTENT (Detail) */}
      <div className="flex-1 flex flex-col min-w-0 bg-slate-950">
         <TaskDetailPanel
            task={selectedTask}
            onClose={() => setSelectedId(null)}
            onSave={handleSaveTask}
         />
      </div>

    </div>
  );
}
