"""fix_schema_Take3

Revision ID: ee44906d5889
Revises: v2_0005
Create Date: 2025-12-30 06:11:00.107909+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import taskman_api.models.action_list

# revision identifiers, used by Alembic.
revision: str = "ee44906d5889"
down_revision: str | Sequence[str] | None = "v2_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check for legacy tables before trying to drop them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "archon_tasks" in tables:
        # Drop archon_tasks FIRST because it depends on archon_projects
        try:
            op.drop_index(op.f("idx_archon_tasks_archived"), table_name="archon_tasks")
            op.drop_index(op.f("idx_archon_tasks_archived_at"), table_name="archon_tasks")
            op.drop_index(op.f("idx_archon_tasks_assignee"), table_name="archon_tasks")
            op.drop_index(op.f("idx_archon_tasks_order"), table_name="archon_tasks")
            op.drop_index(op.f("idx_archon_tasks_project_id"), table_name="archon_tasks")
            op.drop_index(op.f("idx_archon_tasks_status"), table_name="archon_tasks")
            op.drop_table("archon_tasks")
        except Exception:
            pass

    if "archon_code_examples" in tables:
        try:
            op.drop_index(
                op.f("archon_code_examples_embedding_idx"),
                table_name="archon_code_examples",
                postgresql_ops={"embedding": "vector_cosine_ops"},
                postgresql_using="ivfflat",
            )
            op.drop_index(
                op.f("idx_archon_code_examples_content_search"),
                table_name="archon_code_examples",
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_code_examples_content_trgm"),
                table_name="archon_code_examples",
                postgresql_ops={"content": "gin_trgm_ops"},
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_code_examples_metadata"),
                table_name="archon_code_examples",
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_code_examples_source_id"), table_name="archon_code_examples"
            )
            op.drop_index(
                op.f("idx_archon_code_examples_summary_trgm"),
                table_name="archon_code_examples",
                postgresql_ops={"summary": "gin_trgm_ops"},
                postgresql_using="gin",
            )
            op.drop_table("archon_code_examples")
        except Exception:
            pass

    if "archon_document_versions" in tables:
        try:
            op.drop_index(
                op.f("idx_archon_document_versions_created_at"),
                table_name="archon_document_versions",
            )
            op.drop_index(
                op.f("idx_archon_document_versions_field_name"),
                table_name="archon_document_versions",
            )
            op.drop_index(
                op.f("idx_archon_document_versions_project_id"),
                table_name="archon_document_versions",
            )
            op.drop_index(
                op.f("idx_archon_document_versions_task_id"), table_name="archon_document_versions"
            )
            op.drop_index(
                op.f("idx_archon_document_versions_version_number"),
                table_name="archon_document_versions",
            )
            op.drop_table("archon_document_versions")
        except Exception:
            pass

    if "archon_project_sources" in tables:
        try:
            op.drop_index(
                op.f("idx_archon_project_sources_project_id"), table_name="archon_project_sources"
            )
            op.drop_index(
                op.f("idx_archon_project_sources_source_id"), table_name="archon_project_sources"
            )
            op.drop_table("archon_project_sources")
        except Exception:
            pass

    if "archon_projects" in tables:
        try:
            # NOW drop archon_projects
            op.drop_table("archon_projects")
        except Exception:
            pass

    if "archon_crawled_pages" in tables:
        try:
            op.drop_index(
                op.f("archon_crawled_pages_embedding_idx"),
                table_name="archon_crawled_pages",
                postgresql_ops={"embedding": "vector_cosine_ops"},
                postgresql_using="ivfflat",
            )
            op.drop_index(
                op.f("idx_archon_crawled_pages_content_search"),
                table_name="archon_crawled_pages",
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_crawled_pages_content_trgm"),
                table_name="archon_crawled_pages",
                postgresql_ops={"content": "gin_trgm_ops"},
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_crawled_pages_metadata"),
                table_name="archon_crawled_pages",
                postgresql_using="gin",
            )
            op.drop_index(
                op.f("idx_archon_crawled_pages_source_id"), table_name="archon_crawled_pages"
            )
            op.drop_table("archon_crawled_pages")
        except Exception:
            pass

    if "archon_settings" in tables:
        try:
            op.drop_index(op.f("idx_archon_settings_category"), table_name="archon_settings")
            op.drop_index(op.f("idx_archon_settings_key"), table_name="archon_settings")
            op.drop_table("archon_settings")
        except Exception:
            pass

    if "archon_sources" in tables:
        try:
            op.drop_index(op.f("idx_archon_sources_display_name"), table_name="archon_sources")
            op.drop_index(op.f("idx_archon_sources_knowledge_type"), table_name="archon_sources")
            op.drop_index(
                op.f("idx_archon_sources_metadata"),
                table_name="archon_sources",
                postgresql_using="gin",
            )
            op.drop_index(op.f("idx_archon_sources_title"), table_name="archon_sources")
            op.drop_index(op.f("idx_archon_sources_url"), table_name="archon_sources")
            op.drop_table("archon_sources")
        except Exception:
            pass

    if "archon_prompts" in tables:
        try:
            op.drop_index(op.f("idx_archon_prompts_name"), table_name="archon_prompts")
            op.drop_table("archon_prompts")
        except Exception:
            pass

    # NOW handle non-legacy table modifications
    op.add_column("action_lists", sa.Column("name", sa.String(length=255), nullable=False))

    # Drop indexes BEFORE altering columns to avoid GIN opclass errors
    op.drop_index(op.f("idx_action_lists_created_at"), table_name="action_lists")
    op.drop_index(op.f("idx_action_lists_id"), table_name="action_lists")
    op.drop_index(op.f("idx_action_lists_owner"), table_name="action_lists")
    op.drop_index(op.f("idx_action_lists_project_id"), table_name="action_lists")
    op.drop_index(op.f("idx_action_lists_project_status"), table_name="action_lists")
    op.drop_index(op.f("idx_action_lists_sprint_id"), table_name="action_lists")
    op.drop_index(
        op.f("idx_action_lists_tags_gin"), table_name="action_lists", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_action_lists_updated_at"), table_name="action_lists")
    op.add_column("action_lists", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "action_lists",
        sa.Column("task_ids", taskman_api.models.action_list.StringList(), nullable=False),
    )
    op.alter_column(
        "action_lists",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.alter_column(
        "action_lists",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "project_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "action_lists",
        "items",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "evidence_refs",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "parent_deletion_note",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    # Indexes dropped at start of section
    op.create_index("ix_action_lists_completed_at", "action_lists", ["completed_at"], unique=False)
    op.create_index("ix_action_lists_created_at", "action_lists", ["created_at"], unique=False)
    op.create_index("ix_action_lists_due_date", "action_lists", ["due_date"], unique=False)
    op.create_index("ix_action_lists_priority", "action_lists", ["priority"], unique=False)
    op.create_index("ix_action_lists_status", "action_lists", ["status"], unique=False)
    op.create_index(
        "ix_action_lists_status_priority", "action_lists", ["status", "priority"], unique=False
    )
    op.create_index(
        "ix_action_lists_task_ids",
        "action_lists",
        ["task_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("action_lists", "title")
    op.alter_column(
        "checklists",
        "items",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "checklists",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_sessions",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "plan_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "checklist_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "task_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_turns",
        "tool_calls",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_turns",
        "tool_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_turns",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_conv_turns_conv_id"), table_name="conversation_turns")
    op.create_index(
        op.f("ix_conversation_turns_conversation_id"),
        "conversation_turns",
        ["conversation_id"],
        unique=False,
    )
    op.alter_column(
        "plans",
        "steps",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "plans",
        "tags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "plans",
        "extra_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "plans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "plans",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("projects", sa.Column("title", sa.String(length=256), nullable=True))
    op.add_column("projects", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("sponsors", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("stakeholders", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("target_end_date", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("actual_end_date", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("created_utc", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("updated_utc", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("last_health", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("last_heartbeat_utc", sa.String(length=32), nullable=True))
    op.add_column("projects", sa.Column("repositories", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("comms_channels", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("okrs", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("kpis", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("roadmap", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("success_metrics", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("risks", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("assumptions", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("constraints", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("dependencies_external", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("related_projects", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("shared_components", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("governance", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("security_posture", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("compliance_requirements", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("mpv_policy", sa.JSON(), nullable=True))
    op.add_column("projects", sa.Column("tnve_mandate", sa.String(length=128), nullable=True))
    op.add_column("projects", sa.Column("evidence_root", sa.String(length=256), nullable=True))
    op.add_column("projects", sa.Column("evidence_log", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("deleted_at", sa.String(length=32), nullable=True))
    op.alter_column(
        "projects",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=256),
        nullable=True,
    )
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "owner",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "start_date",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=32),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=32),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "projects",
        "sprints",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "projects",
        "team_members",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "projects",
        "labels",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("idx_projects_created_at"), table_name="projects")
    op.drop_index(op.f("idx_projects_id"), table_name="projects")
    op.drop_index(op.f("idx_projects_owner"), table_name="projects")
    op.drop_index(op.f("idx_projects_start_date"), table_name="projects")
    op.drop_index(op.f("idx_projects_updated_at"), table_name="projects")
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.drop_column("projects", "phases")
    op.drop_column("projects", "observability_json")
    op.drop_column("projects", "pending_reason")
    op.drop_column("projects", "blocked_reason")
    op.add_column("sprints", sa.Column("title", sa.String(length=256), nullable=True))
    op.add_column("sprints", sa.Column("project_id", sa.String(length=64), nullable=True))
    op.add_column("sprints", sa.Column("created_utc", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("updated_utc", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("last_health", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("last_heartbeat_utc", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("scope", sa.Text(), nullable=True))
    op.add_column("sprints", sa.Column("scope_type", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("committed_points", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("delivered_points", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("velocity_target", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("velocity_actual", sa.Float(), nullable=True))
    op.add_column("sprints", sa.Column("predictability_pct", sa.Float(), nullable=True))
    op.add_column("sprints", sa.Column("throughput", sa.Float(), nullable=True))
    op.add_column("sprints", sa.Column("burndown_asset", sa.String(length=256), nullable=True))
    op.add_column("sprints", sa.Column("ceremonies", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("planning_notes", sa.Text(), nullable=True))
    op.add_column("sprints", sa.Column("standup_cadence", sa.String(length=32), nullable=True))
    op.add_column("sprints", sa.Column("review_demo_link", sa.String(length=256), nullable=True))
    op.add_column("sprints", sa.Column("retro_notes", sa.Text(), nullable=True))
    op.add_column("sprints", sa.Column("risks", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("dependencies", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("sprints", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("related_projects", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("shared_components", sa.JSON(), nullable=True))
    op.add_column("sprints", sa.Column("evidence_log", sa.Text(), nullable=True))
    op.add_column("sprints", sa.Column("deleted_at", sa.String(length=32), nullable=True))
    op.alter_column(
        "sprints",
        "id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "sprints",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=256),
        nullable=True,
    )
    op.alter_column(
        "sprints",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "cadence",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "start_date",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "end_date",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=32),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "sprints",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=32),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "sprints",
        "observability",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_sprints_created_at"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_end_date"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_id"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_owner"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_primary_project"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_project_status"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_start_date"), table_name="sprints")
    op.drop_index(op.f("idx_sprints_updated_at"), table_name="sprints")
    op.create_index(op.f("ix_sprints_project_id"), "sprints", ["project_id"], unique=False)
    op.create_index(op.f("ix_sprints_status"), "sprints", ["status"], unique=False)
    op.drop_constraint(op.f("sprints_primary_project_fkey"), "sprints", type_="foreignkey")
    op.drop_column("sprints", "tasks")
    op.drop_column("sprints", "timezone")
    op.drop_column("sprints", "blocked_reason")
    op.drop_column("sprints", "carried_over_points")
    op.drop_column("sprints", "primary_project")
    op.drop_column("sprints", "metrics")
    op.drop_column("sprints", "actual_points")
    op.drop_column("sprints", "imported_tasks")
    op.drop_column("sprints", "velocity_target_points")
    op.drop_column("sprints", "phases")
    op.drop_column("sprints", "definition_of_done")
    op.drop_column("sprints", "pending_reason")
    op.drop_column("sprints", "scope_changes")
    # Indexes dropped at start of tasks section to avoid GIN errors
    op.drop_index(op.f("idx_tasks_assignees_gin"), table_name="tasks", postgresql_using="gin")
    op.drop_index(op.f("idx_tasks_blocks_gin"), table_name="tasks", postgresql_using="gin")
    op.drop_index(op.f("idx_tasks_created_at"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_depends_on_gin"), table_name="tasks", postgresql_using="gin")
    op.drop_index(op.f("idx_tasks_id"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_labels_gin"), table_name="tasks", postgresql_using="gin")
    op.drop_index(op.f("idx_tasks_project_status"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_sprint_status"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_status_priority"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_updated_at"), table_name="tasks")

    op.add_column("tasks", sa.Column("project_id", sa.String(length=50), nullable=True))
    op.add_column("tasks", sa.Column("sprint_id", sa.String(length=50), nullable=True))
    op.add_column("tasks", sa.Column("assignee", sa.String(length=100), nullable=True))
    op.add_column("tasks", sa.Column("estimated_hours", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("actual_hours", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("story_points", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("labels", sa.JSON(), nullable=False))
    op.add_column("tasks", sa.Column("tags", sa.Text(), nullable=True))
    op.add_column(
        "tasks", sa.Column("last_heartbeat_utc", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column("tasks", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "tasks",
        "assignees",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column("tasks", "priority", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column(
        "tasks",
        "primary_project",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "related_projects",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "related_sprints",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "parents",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "depends_on",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "blocks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "blockers",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "acceptance_criteria",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "definition_of_done",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "quality_gates",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "verification",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "actions_taken",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "related_links",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "automation_candidate",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tasks",
        "risks",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "observability",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    # Indexes dropped at start of section
    op.create_index(op.f("ix_tasks_primary_project"), "tasks", ["primary_project"], unique=False)
    op.create_index(op.f("ix_tasks_primary_sprint"), "tasks", ["primary_sprint"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_sprint_id"), "tasks", ["sprint_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.drop_constraint(op.f("tasks_primary_sprint_fkey"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("tasks_primary_project_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "phases")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "phases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"testing": {"status": "not_started", "tests_passing": false, "has_unit_tests": false}, "planning": {"status": "not_started", "has_definition_of_done": false, "has_acceptance_criteria": false}, "research": {"status": "not_started", "has_research": false, "research_adequate": false}, "implementation": {"status": "not_started", "progress_pct": 0, "has_code_changes": false}}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("tasks_primary_project_fkey"),
        "tasks",
        "projects",
        ["primary_project"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("tasks_primary_sprint_fkey"),
        "tasks",
        "sprints",
        ["primary_sprint"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_sprint_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_primary_sprint"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_primary_project"), table_name="tasks")
    op.create_index(op.f("idx_tasks_updated_at"), "tasks", ["updated_at"], unique=False)
    op.create_index(
        op.f("idx_tasks_status_priority"), "tasks", ["status", "priority"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_sprint_status"), "tasks", ["primary_sprint", "status"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_project_status"), "tasks", ["primary_project", "status"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_labels_gin"),
        "tasks",
        ["related_links"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(
        op.f("idx_tasks_depends_on_gin"),
        "tasks",
        ["depends_on"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(
        op.f("idx_tasks_blocks_gin"), "tasks", ["blocks"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_tasks_assignees_gin"),
        "tasks",
        ["assignees"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "tasks",
        "observability",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "risks",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "automation_candidate",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tasks",
        "related_links",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "actions_taken",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "verification",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "quality_gates",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "definition_of_done",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "acceptance_criteria",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "blockers",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "blocks",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "depends_on",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "parents",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "related_sprints",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "related_projects",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "primary_project",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column("tasks", "priority", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column(
        "tasks",
        "assignees",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column("tasks", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("tasks", "last_heartbeat_utc")
    op.drop_column("tasks", "tags")
    op.drop_column("tasks", "labels")
    op.drop_column("tasks", "due_date")
    op.drop_column("tasks", "story_points")
    op.drop_column("tasks", "actual_hours")
    op.drop_column("tasks", "estimated_hours")
    op.drop_column("tasks", "assignee")
    op.drop_column("tasks", "sprint_id")
    op.drop_column("tasks", "project_id")
    op.add_column(
        "sprints",
        sa.Column(
            "scope_changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column("pending_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "definition_of_done",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "phases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"planning": {"status": "not_started", "has_sprint_goal": false, "tasks_estimated": false, "has_capacity_plan": false}, "implementation": {"status": "not_started", "tasks_total": 0, "progress_pct": 0, "tasks_completed": 0}}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "velocity_target_points",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "imported_tasks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "actual_points", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column("primary_project", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sprints",
        sa.Column(
            "carried_over_points",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "sprints",
        sa.Column("blocked_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sprints", sa.Column("timezone", sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.add_column(
        "sprints",
        sa.Column(
            "tasks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("sprints_primary_project_fkey"),
        "sprints",
        "projects",
        ["primary_project"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_sprints_status"), table_name="sprints")
    op.drop_index(op.f("ix_sprints_project_id"), table_name="sprints")
    op.create_index(op.f("idx_sprints_updated_at"), "sprints", ["updated_at"], unique=False)
    op.create_index(op.f("idx_sprints_start_date"), "sprints", ["start_date"], unique=False)
    op.create_index(
        op.f("idx_sprints_project_status"), "sprints", ["primary_project", "status"], unique=False
    )
    op.create_index(
        op.f("idx_sprints_primary_project"), "sprints", ["primary_project"], unique=False
    )
    op.create_index(op.f("idx_sprints_owner"), "sprints", ["owner"], unique=False)
    op.create_index(op.f("idx_sprints_id"), "sprints", ["id"], unique=False)
    op.create_index(op.f("idx_sprints_end_date"), "sprints", ["end_date"], unique=False)
    op.create_index(op.f("idx_sprints_created_at"), "sprints", ["created_at"], unique=False)
    op.alter_column(
        "sprints",
        "observability",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "sprints",
        "updated_at",
        existing_type=sa.String(length=32),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "sprints",
        "created_at",
        existing_type=sa.String(length=32),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "sprints",
        "end_date",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "start_date",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "cadence",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "status",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "sprints",
        "name",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "sprints",
        "id",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("sprints", "deleted_at")
    op.drop_column("sprints", "evidence_log")
    op.drop_column("sprints", "shared_components")
    op.drop_column("sprints", "related_projects")
    op.drop_column("sprints", "sprints")
    op.drop_column("sprints", "dependencies")
    op.drop_column("sprints", "risks")
    op.drop_column("sprints", "retro_notes")
    op.drop_column("sprints", "review_demo_link")
    op.drop_column("sprints", "standup_cadence")
    op.drop_column("sprints", "planning_notes")
    op.drop_column("sprints", "ceremonies")
    op.drop_column("sprints", "burndown_asset")
    op.drop_column("sprints", "throughput")
    op.drop_column("sprints", "predictability_pct")
    op.drop_column("sprints", "velocity_actual")
    op.drop_column("sprints", "velocity_target")
    op.drop_column("sprints", "delivered_points")
    op.drop_column("sprints", "committed_points")
    op.drop_column("sprints", "scope_type")
    op.drop_column("sprints", "scope")
    op.drop_column("sprints", "last_heartbeat_utc")
    op.drop_column("sprints", "last_health")
    op.drop_column("sprints", "updated_utc")
    op.drop_column("sprints", "created_utc")
    op.drop_column("sprints", "project_id")
    op.drop_column("sprints", "title")
    op.add_column(
        "projects",
        sa.Column("blocked_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("pending_reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "observability_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "phases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"planning": {"status": "not_started", "has_prd": false, "has_roadmap": false, "has_architecture": false}, "research": {"status": "not_started", "research_adequate": false, "has_market_research": false, "has_technical_research": false}}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.create_index(op.f("idx_projects_updated_at"), "projects", ["updated_at"], unique=False)
    op.create_index(op.f("idx_projects_start_date"), "projects", ["start_date"], unique=False)
    op.create_index(op.f("idx_projects_owner"), "projects", ["owner"], unique=False)
    op.create_index(op.f("idx_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("idx_projects_created_at"), "projects", ["created_at"], unique=False)
    op.alter_column(
        "projects",
        "labels",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "projects",
        "team_members",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "projects",
        "sprints",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=sa.String(length=32),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=sa.String(length=32),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "projects",
        "start_date",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "owner",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "name",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("projects", "deleted_at")
    op.drop_column("projects", "evidence_log")
    op.drop_column("projects", "evidence_root")
    op.drop_column("projects", "tnve_mandate")
    op.drop_column("projects", "mpv_policy")
    op.drop_column("projects", "compliance_requirements")
    op.drop_column("projects", "security_posture")
    op.drop_column("projects", "governance")
    op.drop_column("projects", "shared_components")
    op.drop_column("projects", "related_projects")
    op.drop_column("projects", "dependencies_external")
    op.drop_column("projects", "constraints")
    op.drop_column("projects", "assumptions")
    op.drop_column("projects", "risks")
    op.drop_column("projects", "success_metrics")
    op.drop_column("projects", "roadmap")
    op.drop_column("projects", "kpis")
    op.drop_column("projects", "okrs")
    op.drop_column("projects", "comms_channels")
    op.drop_column("projects", "repositories")
    op.drop_column("projects", "last_heartbeat_utc")
    op.drop_column("projects", "last_health")
    op.drop_column("projects", "updated_utc")
    op.drop_column("projects", "created_utc")
    op.drop_column("projects", "actual_end_date")
    op.drop_column("projects", "target_end_date")
    op.drop_column("projects", "stakeholders")
    op.drop_column("projects", "sponsors")
    op.drop_column("projects", "description")
    op.drop_column("projects", "title")
    op.alter_column(
        "plans",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "plans",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "plans",
        "extra_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "plans",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "plans",
        "steps",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("ix_conversation_turns_conversation_id"), table_name="conversation_turns")
    op.create_index(
        op.f("idx_conv_turns_conv_id"), "conversation_turns", ["conversation_id"], unique=False
    )
    op.alter_column(
        "conversation_turns",
        "extra_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "conversation_turns",
        "tool_results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_turns",
        "tool_calls",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_sessions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_sessions",
        "task_ids",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "checklist_ids",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "plan_ids",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "extra_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "conversation_sessions",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "checklists",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "checklists",
        "extra_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "checklists",
        "items",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.add_column(
        "action_lists",
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_action_lists_task_ids", table_name="action_lists", postgresql_using="gin")
    op.drop_index("ix_action_lists_status_priority", table_name="action_lists")
    op.drop_index("ix_action_lists_status", table_name="action_lists")
    op.drop_index("ix_action_lists_priority", table_name="action_lists")
    op.drop_index("ix_action_lists_due_date", table_name="action_lists")
    op.drop_index("ix_action_lists_created_at", table_name="action_lists")
    op.drop_index("ix_action_lists_completed_at", table_name="action_lists")
    op.create_index(
        op.f("idx_action_lists_updated_at"), "action_lists", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("idx_action_lists_tags_gin"),
        "action_lists",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_action_lists_sprint_id"), "action_lists", ["sprint_id"], unique=False)
    op.create_index(
        op.f("idx_action_lists_project_status"),
        "action_lists",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_action_lists_project_id"), "action_lists", ["project_id"], unique=False
    )
    op.create_index(op.f("idx_action_lists_owner"), "action_lists", ["owner"], unique=False)
    op.create_index(op.f("idx_action_lists_id"), "action_lists", ["id"], unique=False)
    op.create_index(
        op.f("idx_action_lists_created_at"), "action_lists", ["created_at"], unique=False
    )
    op.alter_column(
        "action_lists",
        "parent_deletion_note",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "extra_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "evidence_refs",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "items",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "project_id",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "action_lists",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "action_lists",
        "status",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.drop_column("action_lists", "task_ids")
    op.drop_column("action_lists", "description")
    op.drop_column("action_lists", "name")
    op.create_table(
        "archon_prompts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("prompt_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_prompts_pkey")),
        sa.UniqueConstraint(
            "prompt_name",
            name=op.f("archon_prompts_prompt_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_archon_prompts_name"), "archon_prompts", ["prompt_name"], unique=False
    )
    op.create_table(
        "archon_sources",
        sa.Column(
            "source_id",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="Unique hash identifier for the source (16-char SHA256 hash of URL)",
        ),
        sa.Column(
            "source_url",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="The original URL that was crawled to create this source",
        ),
        sa.Column(
            "source_display_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment='Human-readable name for UI display (e.g., "GitHub - microsoft/typescript")',
        ),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "total_word_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment='Descriptive title for the source (e.g., "Pydantic AI API Reference")',
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
            comment="JSONB field storing knowledge_type, tags, and other metadata",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_id", name="archon_sources_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_archon_sources_url"), "archon_sources", ["source_url"], unique=False)
    op.create_index(op.f("idx_archon_sources_title"), "archon_sources", ["title"], unique=False)
    op.create_index(
        op.f("idx_archon_sources_metadata"),
        "archon_sources",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_sources_knowledge_type"),
        "archon_sources",
        [sa.literal_column("(metadata ->> 'knowledge_type'::text)")],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_sources_display_name"),
        "archon_sources",
        ["source_display_name"],
        unique=False,
    )
    op.create_table(
        "archon_settings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("encrypted_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_encrypted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_settings_pkey")),
        sa.UniqueConstraint(
            "key",
            name=op.f("archon_settings_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Stores application configuration including API keys, RAG settings, and code extraction parameters",
    )
    op.create_index(op.f("idx_archon_settings_key"), "archon_settings", ["key"], unique=False)
    op.create_index(
        op.f("idx_archon_settings_category"), "archon_settings", ["category"], unique=False
    )
    op.create_table(
        "archon_tasks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("parent_task_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "description",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("todo", "doing", "review", "done", name="task_status"),
            server_default=sa.text("'todo'::task_status"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "assignee",
            sa.TEXT(),
            server_default=sa.text("'User'::text"),
            autoincrement=False,
            nullable=True,
            comment='The agent or user assigned to this task. Can be any valid agent name or "User"',
        ),
        sa.Column(
            "task_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("feature", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "code_examples",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
            comment="Soft delete flag - TRUE if task is archived/deleted",
        ),
        sa.Column(
            "archived_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Timestamp when task was archived",
        ),
        sa.Column(
            "archived_by",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="User/system that archived the task",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "assignee IS NOT NULL AND assignee <> ''::text", name="archon_tasks_assignee_check"
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["archon_tasks.id"],
            name="archon_tasks_parent_task_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["archon_projects.id"],
            name="archon_tasks_project_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="archon_tasks_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_archon_tasks_status"), "archon_tasks", ["status"], unique=False)
    op.create_index(
        op.f("idx_archon_tasks_project_id"), "archon_tasks", ["project_id"], unique=False
    )
    op.create_index(op.f("idx_archon_tasks_order"), "archon_tasks", ["task_order"], unique=False)
    op.create_index(op.f("idx_archon_tasks_assignee"), "archon_tasks", ["assignee"], unique=False)
    op.create_index(
        op.f("idx_archon_tasks_archived_at"), "archon_tasks", ["archived_at"], unique=False
    )
    op.create_index(op.f("idx_archon_tasks_archived"), "archon_tasks", ["archived"], unique=False)
    op.create_table(
        "archon_crawled_pages",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("chunk_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "content_search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["archon_sources.source_id"],
            name=op.f("archon_crawled_pages_source_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_crawled_pages_pkey")),
        sa.UniqueConstraint(
            "url",
            "chunk_number",
            name=op.f("archon_crawled_pages_url_chunk_number_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_archon_crawled_pages_source_id"),
        "archon_crawled_pages",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_crawled_pages_metadata"),
        "archon_crawled_pages",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_crawled_pages_content_trgm"),
        "archon_crawled_pages",
        ["content"],
        unique=False,
        postgresql_ops={"content": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_crawled_pages_content_search"),
        "archon_crawled_pages",
        ["content_search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("archon_crawled_pages_embedding_idx"),
        "archon_crawled_pages",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.create_table(
        "archon_projects",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "description",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "docs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "features",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("github_repo", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "pinned",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="archon_projects_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "archon_project_sources",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("source_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "linked_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.TEXT(),
            server_default=sa.text("'system'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["archon_projects.id"],
            name=op.f("archon_project_sources_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_project_sources_pkey")),
        sa.UniqueConstraint(
            "project_id",
            "source_id",
            name=op.f("archon_project_sources_project_id_source_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_archon_project_sources_source_id"),
        "archon_project_sources",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_project_sources_project_id"),
        "archon_project_sources",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "archon_document_versions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "task_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="DEPRECATED: No longer used for new versions, kept for historical task version data",
        ),
        sa.Column(
            "field_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="Name of JSONB field being versioned (docs, features, data) - task fields and prd removed as unused",
        ),
        sa.Column("version_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            comment="Full snapshot of field content at this version",
        ),
        sa.Column("change_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "change_type",
            sa.TEXT(),
            server_default=sa.text("'update'::text"),
            autoincrement=False,
            nullable=True,
            comment="Type of change: create, update, delete, restore, backup",
        ),
        sa.Column(
            "document_id",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="For docs arrays, the specific document ID that was changed",
        ),
        sa.Column(
            "created_by",
            sa.TEXT(),
            server_default=sa.text("'system'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "project_id IS NOT NULL AND task_id IS NULL OR project_id IS NULL AND task_id IS NOT NULL",
            name=op.f("chk_project_or_task"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["archon_projects.id"],
            name=op.f("archon_document_versions_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["archon_tasks.id"],
            name=op.f("archon_document_versions_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_document_versions_pkey")),
        sa.UniqueConstraint(
            "project_id",
            "task_id",
            "field_name",
            "version_number",
            name=op.f("archon_document_versions_project_id_task_id_field_name_vers_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Version control for JSONB fields in projects only - task versioning has been removed to simplify MCP operations",
    )
    op.create_index(
        op.f("idx_archon_document_versions_version_number"),
        "archon_document_versions",
        ["version_number"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_document_versions_task_id"),
        "archon_document_versions",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_document_versions_project_id"),
        "archon_document_versions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_document_versions_field_name"),
        "archon_document_versions",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_document_versions_created_at"),
        "archon_document_versions",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "archon_code_examples",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("chunk_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "content_search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, ((content || ' '::text) || COALESCE(summary, ''::text)))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["archon_sources.source_id"],
            name=op.f("archon_code_examples_source_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("archon_code_examples_pkey")),
        sa.UniqueConstraint(
            "url",
            "chunk_number",
            name=op.f("archon_code_examples_url_chunk_number_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_archon_code_examples_summary_trgm"),
        "archon_code_examples",
        ["summary"],
        unique=False,
        postgresql_ops={"summary": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_code_examples_source_id"),
        "archon_code_examples",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_archon_code_examples_metadata"),
        "archon_code_examples",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_code_examples_content_trgm"),
        "archon_code_examples",
        ["content"],
        unique=False,
        postgresql_ops={"content": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_archon_code_examples_content_search"),
        "archon_code_examples",
        ["content_search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("archon_code_examples_embedding_idx"),
        "archon_code_examples",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    # ### end Alembic commands ###
