-- Batch patch for projects table to match SQLAlchemy model

ALTER TABLE projects ADD COLUMN IF NOT EXISTS title VARCHAR(256);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS mission TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS owner VARCHAR(128);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS sponsors JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS stakeholders JSONB;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS target_end_date VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS actual_end_date VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_at VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_utc VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_utc VARCHAR(32);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS last_health VARCHAR(32);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS last_heartbeat_utc VARCHAR(32);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS repositories JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS comms_channels JSONB;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS okrs JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS kpis JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS roadmap JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS success_metrics JSONB;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS risks JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS assumptions JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS constraints JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS dependencies_external JSONB;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS sprints JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS related_projects JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS shared_components JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS team_members JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS labels JSONB;

ALTER TABLE projects ADD COLUMN IF NOT EXISTS governance JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS security_posture JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS compliance_requirements JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS mpv_policy JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tnve_mandate VARCHAR(128);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS evidence_root VARCHAR(256);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS evidence_log TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deleted_at VARCHAR(32);
